name: Build an Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
              with:
                  persist-credentials: false
            - name: Install and Build
              run: |
                  yarn install
                  yarn build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.DEPLOY }}
                  folder: docs/dist/.vuepress/dist
                  branch: gh-pages
                  repository-name: WangXingWeb/Nblog
